version: '2.17'

volumes:
  pg_data:

services:
  database:
    container_name: postgres_container
    image: postgres:15.2-alpine
    environment:
      - POSTGRES_USER=${DATABASE_USER}
      - POSTGRES_PASSWORD=${DATABASE_PASSWORD}
      - POSTGRES_DB=mycompras
    ports:
      - "5433:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data
